name: test
description: test python project with pytest

runs:
  using: composite
  steps:
    - name: run pytest and generate code coverage report
      run: |
        pdm run pytest tests -v --cache-clear --junitxml=./coverage_report.xml
      shell: bash
    # using: https://github.com/dorny/test-reporter
    - name: test coverage report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Python Tests            # Name of the check run which will be created
        path: ./coverage_report.xml    # Path to test results
        reporter: java-junit
