# reference: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: dependencies
description: prepare for required python dependencies

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.9'

runs:
  using: composite
  steps:
    - name: setup the python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies for testing
      run: pdm sync -d -G test
      shell: bash
