name: 'Python Push Check'

on:
  push:
    paths:
      - '**.py'

# reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
jobs:
  check-pull-request:
    uses: ./.github/workflows/python_test.yaml
