name: Test Python Project

on: workflow_call

jobs:
  test-python-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: run Python dependencies action
        uses: ./.github/actions/python_dependencies
        with:
          python-version: '3.9'
      - name: run Python test action
        uses: ./.github/actions/python_test
